{
    'name':"Entech custom changes",
    'version':'2.6',
    'summary':'Creating various fields in the sale and purchase',
    'description':"module for the management of sales and purchases",
    'author': 'AGM Global Services',
    'website': 'https://www.agmglobal.co/',
    'licence': 'OPL-1',
    'depends':['base','sale','stock','account','purchase','sale_stock','product'],
    'data':['views/sale_order_view.xml',
             'views/stock_picking_view.xml',
             'views/purchase_order_view.xml',
             'views/account_move_view.xml',
             'views/res_partner.xml',
             'views/product_category.xml',
             'reports/sale_report.xml',
            'reports/invoice_report.xml',
            'reports/delivery_report.xml',
            'reports/purchase_order_report.xml',
            'reports/receipt_report.xml',
            'reports/bill_report.xml',
            'security/ir_rule.xml',
            ],
    'installable':True,
    'application':False,


}