from . import product_component
from . import product_template
from . import product_part
from . import stock_move_line
from . import stock_move
from . import res_partner
from . import stock_production_lot
from . import stock_lot_component_line
from . import account_move
from . import account_move_line
from . import sale_order
from . import stock_picking